apiVersion: v1
kind: Secret
metadata:
  name: default-apps
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git://git@github.com:dslaterak/k8s-bootstrap.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    
    -----END OPENSSH PRIVATE KEY-----
