apiVersion: v1
kind: Secret
metadata:
  name: git-repo-secret
  namespace: argocd
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNELzI4U25QTzl2YSszaThQR2xYQy9KaENzYVpCWG51Z3ByNGs2Snd0VWgzd0FBQUpqUzFaRVAwdFdSCkR3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRC8yOFNuUE85dmErM2k4UEdsWEMvSmhDc2FaQlhudWdwcjRrNkp3dFVoM3cKQUFBRUJocEJMNjgzYXhLRUhjd0RwVW01YUtuMzBwZjhIYzZ0a3F2cTRnTHhDakFmL2J4S2M4NzI5cjdlTHc4YVZjTDhtRQpLeHBrRmVlNkNtdmlUb25DMVNIZkFBQUFFV1JoYmk1emJHRjBaWEpBYldVdVkyOXRBUUlEQkE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K