apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 31.0.0